#Version: 1.0
#Author: MCAzertox

#Don't forget to check other config files like "levels.yml" , "messages.yml" and "boosters.yml"

main-config:
  hoe-name: "&aHarvestHoe"
  #The name of the harvestHoe (it shoud be the same to open the menu)
  
  glowing: true
  
  hoe-lore: 
    - "&7&m-------------&aHarvestHoe&7&m-------------"
    - ""
    - "&5*&bUse this hoe to harvest crops !"
    - "&bIt will automatically sell the harvested resources !"
    - ""
    - "&eTips:"
    - "&6- &dyou can use &c/hh safemode &dto only breaks ripe crops !"
    - "&6- &ddepends on your level, you can &cinstant break &dblocks like &cpumpkins or melons &d!"
    - "&6- &dsell prices depends of your harvest hoe level !"
    - ""
    - "&7&l(&eRight-Click to upgrade !&7&l)"
    - ""
    - "&7&m------------------------------"
  
  open-permission: "harvesthoe.open"
  #Here is the permission the player should have to open the menu
  requires-permission: false
  no-perm-message: "&cYou don't have the permission to open the harvest menu !"
  
  enable-open-menu-message: true
  #If true a message will be appears in the chat for the player
  
  open-menu-message: "&eOpening the menu..."
  #The message when a player open the menu
  
  prefix: "&7[&aHarvestHoe&7] "
  
  #%level-clicked% --> level the player clicked
  #%level-player% --> level the player have
  level-already-unlocked-message: "&cYou are already level &b%level-clicked% &c!"
  level-above-unlocked-message: "&cYou are level &b%level-player% &cso you cannot buy level &b%level-clicked% &c!"
  
  #%level-required% --> level the player need to have
  buy-lower-level-first-message: "&cPlease buy level &b%level-required% &cfirst !"
  
  #%level% --> %to-level%
  levelup-message: "&bYou successfuly upgrade your Harvest Hoe: &a%level% &b➽  &a%to-level%"
  not-enought-money-message: "&cYou don't have enought money to upgrade to level &a%to-level%"
  
  open-sound:
    #The sound played when the player open the menu
    enabled: true
    sound: ENTITY_EXPERIENCE_ORB_PICKUP

  safe-mode: #Safe mode give you the ability to not break crops when they are not mature
    enabled: true
    enable-message: "&7Safe mode &aEnabled !"
    disable-message: "&7Safe mode &cDisabled !"
    permission-require:
      enabled: true
      permission: "harvesthoe.safemode"

sounds: #Sound played when breaking a block
  #For all the sounds, please use this list: https://helpch.at/docs/1.16.2/org/bukkit/Sound.html
  
  scane:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  wheat:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  carrots:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  potatoes:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  melons:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  pumpkins:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  netherwarts:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  cocoabeans:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  beetroots:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_BELL
  
gui:
  gui-name: "&a&lHarvest Hoe GUI"
  
  gui-size: 27
  #Can be 9, 18, 27, 36, 46, 54
  
  quit:
    title: "&cQuit"
    material: REDSTONE_BLOCK
    lore:
      - "&cClose this GUI"
      - ""
      - "&7(Left-Click)"
    #To write on a new line, put ";;" symbol
    slot: 26
    
  filler: #Use this to fill empty spaces if u want
    1:
      title: " "
      material: GRAY_STAINED_GLASS_PANE
      glowing: true
      lore:
        - ""
      slots: "0,1,2,3,4,5,6,7,8,9,17,18,19,20,21,22,23,24,25"
      #To put multiple slots, please use ","
    2:
      title: " "
      material: RED_STAINED_GLASS_PANE
      glowing: false
      lore:
        - ""
      slots: "10,12,14,16"
      #To put multiple slots, please use ","

#YOU CAN CONFIG LEVELS IN "levels.yml" !!!!!

    
    
    